version: '3.8'

services:
  web:
    build: ./expenses
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./expenses/:/usr/src/expenses/
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=psql_db

volumes:
  postgres_data: