# Generated by Django 4.2.3 on 2024-02-10 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_add_expenses_and_category_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
